=== IRT-Open-Source/scf/modules/STLXML-XSD/stlxml.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- 
Copyright 2014 Institut fÃ¼r Rundfunktechnik GmbH, Munich, Germany

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, the subject work
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="StlXml">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="HEAD"/>
        <xs:element ref="BODY"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="HEAD">
    <xs:complexType>
      <xs:sequence>
        <xs:element minOccurs="0" name="metadata">
          <xs:complexType>
            <xs:sequence>
              <xs:any minOccurs="1" maxOccurs="unbounded" processContents="lax"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element ref="GSI"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="GSI">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="CPN"/>
        <xs:element ref="DFC"/>
        <xs:element ref="DSC"/>
        <xs:element ref="CCT"/>
        <xs:element ref="LC"/>
        <xs:element ref="OPT"/>
        <xs:element ref="OET"/>
        <xs:element ref="TPT"/>
        <xs:element ref="TET"/>
        <xs:element ref="TN"/>
        <xs:element ref="TCD"/>
        <xs:element ref="SLR"/>
        <xs:element ref="CD"/>
        <xs:element ref="RD"/>
        <xs:element ref="RN"/>
        <xs:element ref="TNB"/>
        <xs:element ref="TNS"/>
        <xs:element ref="TNG"/>
        <xs:element ref="MNC"/>
        <xs:element ref="MNR"/>
        <xs:element ref="TCS"/>
        <xs:element ref="TCP"/>
        <xs:element ref="TCF"/>
        <xs:element ref="TND"/>
        <xs:element ref="DSN"/>
        <xs:element ref="CO"/>
        <xs:element ref="PUB"/>
        <xs:element ref="EN"/>
        <xs:element ref="ECD"/>
        <xs:element ref="UDA"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="CPN">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="437"/>
        <xs:enumeration value="850"/>
        <xs:enumeration value="860"/>
        <xs:enumeration value="863"/>
        <xs:enumeration value="865"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="DFC">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="STL25.01"/>
        <xs:enumeration value="STL30.01"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="DSC">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value=""/>
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
        <xs:enumeration value="2"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="CCT">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="00"/>
        <xs:enumeration value="01"/>
        <xs:enumeration value="02"/>
        <xs:enumeration value="03"/>
        <xs:enumeration value="04"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="LC">
    <xs:simpleType>
      <xs:restriction base="xs:hexBinary">
        <xs:length value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:simpleType name="String32">
    <xs:restriction base="xs:string">
      <xs:maxLength value="32"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="String16">
    <xs:restriction base="xs:string">
      <xs:maxLength value="16"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="String6">
    <xs:restriction base="xs:string">
      <xs:maxLength value="6"/>
    </xs:restriction>
  </xs:simpleType>
  <xs:simpleType name="timeCodeFormat">
    <xs:restriction base="xs:token">
      <xs:pattern
        value="(00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23)[0-5][0-9][0-5][0-9](00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29)"
      />
    </xs:restriction>
  </xs:simpleType>
  <xs:element name="OPT" type="String32"/>
  <xs:element name="OET" type="String32"/>
  <xs:element name="TPT" type="String32"/>
  <xs:element name="TET" type="String32"/>
  <xs:element name="TN" type="String32"/>
  <xs:element name="TCD" type="String32"/>
  <xs:element name="SLR" type="String16"/>
  <xs:element name="CD" type="String6"/>
  <xs:element name="RD" type="String6"/>
  <xs:element name="RN">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TNB">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99999"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TNS">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99999"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TNG">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="255"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="MNC">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="MNR">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TCS">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:enumeration value="0"/>
        <xs:enumeration value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TCP" type="timeCodeFormat"/>
  <xs:element name="TCF" type="timeCodeFormat"/>
  <xs:element name="TND">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="9"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="DSN">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="1"/>
        <xs:maxInclusive value="9"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="CO">
    <xs:simpleType>
      <xs:restriction base="xs:token">
        <xs:pattern value="[A-z]{3}"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="PUB" type="String32"/>
  <xs:element name="EN" type="String32"/>
  <xs:element name="ECD" type="String32"/>
  <xs:element name="UDA">
    <xs:simpleType>
      <xs:restriction base="xs:string">
        <!-- 576 bytes coded in Base64 -->
        <xs:maxLength value="768"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="BODY">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TTICONTAINER"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TTICONTAINER">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="TTI" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="TTI">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="SGN"/>
        <xs:element ref="SN"/>
        <xs:element ref="EBN"/>
        <xs:element ref="CS"/>
        <xs:element ref="TCI"/>
        <xs:element ref="TCO"/>
        <xs:element ref="VP"/>
        <xs:element ref="JC"/>
        <xs:element ref="CF"/>
        <xs:element ref="TF"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="SGN">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="255"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="SN">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="65535"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="EBN">
    <xs:simpleType>
      <xs:restriction base="xs:hexBinary">
        <xs:length value="1"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="CS">
    <xs:simpleType>
      <xs:restriction base="xs:hexBinary">
        <xs:enumeration value="00"/>
        <xs:enumeration value="01"/>
        <xs:enumeration value="02"/>
        <xs:enumeration value="03"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TCI" type="timeCodeFormat"/>
  <xs:element name="TCO" type="timeCodeFormat"/>
  <xs:element name="VP">
    <xs:simpleType>
      <xs:restriction base="xs:nonNegativeInteger">
        <xs:minInclusive value="0"/>
        <xs:maxInclusive value="99"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="JC">
    <xs:simpleType>
      <xs:restriction base="xs:hexBinary">
        <xs:enumeration value="00"/>
        <xs:enumeration value="01"/>
        <xs:enumeration value="02"/>
        <xs:enumeration value="03"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="CF">
    <xs:simpleType>
      <xs:restriction base="xs:hexBinary">
        <xs:enumeration value="00"/>
        <xs:enumeration value="01"/>
      </xs:restriction>
    </xs:simpleType>
  </xs:element>
  <xs:element name="TF">
    <xs:complexType mixed="true">
      <xs:choice minOccurs="0" maxOccurs="unbounded">
        <xs:element ref="AlphaWhite"/>
        <xs:element ref="AlphaBlack"/>
        <xs:element ref="AlphaBlue"/>
        <xs:element ref="AlphaCyan"/>
        <xs:element ref="AlphaGreen"/>
        <xs:element ref="AlphaMagenta"/>
        <xs:element ref="AlphaRed"/>
        <xs:element ref="AlphaYellow"/>
        <xs:element ref="BlackBackground"/>
        <xs:element ref="Conceal"/>
        <xs:element ref="ContiguousMosaic"/>
        <xs:element ref="DoubleHeight"/>
        <xs:element ref="DoubleSize"/>
        <xs:element ref="DoubleWidth"/>
        <xs:element ref="EndBox"/>
        <xs:element ref="Flash"/>
        <xs:element ref="HoldMosaic"/>
        <xs:element ref="MosaicBlack"/>
        <xs:element ref="MosaicBlue"/>
        <xs:element ref="MosaicCyan"/>
        <xs:element ref="MosaicGreen"/>
        <xs:element ref="MosaicMagenta"/>
        <xs:element ref="MosaicRed"/>
        <xs:element ref="MosaicWhite"/>
        <xs:element ref="MosaicYellow"/>
        <xs:element ref="NewBackground"/>
        <xs:element ref="NormalHeight"/>
        <xs:element ref="ReleaseMosaic"/>
        <xs:element ref="Reserved"/>
        <xs:element ref="SeparatedMosaic"/>
        <xs:element ref="StartBox"/>
        <xs:element ref="Steady"/>
        <xs:element ref="newline"/>
        <xs:element ref="space"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="AlphaBlack">
    <xs:complexType/>
  </xs:element>
  <xs:element name="AlphaWhite">
    <xs:complexType/>
  </xs:element>
  <xs:element name="AlphaBlue">
    <xs:complexType/>
  </xs:element>
  <xs:element name="AlphaCyan">
    <xs:complexType/>
  </xs:element>
  <xs:element name="AlphaGreen">
    <xs:complexType/>
  </xs:element>
  <xs:element name="AlphaMagenta">
    <xs:complexType/>
  </xs:element>
  <xs:element name="AlphaRed">
    <xs:complexType/>
  </xs:element>
  <xs:element name="AlphaYellow">
    <xs:complexType/>
  </xs:element>
  <xs:element name="BlackBackground">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Conceal">
    <xs:complexType/>
  </xs:element>
  <xs:element name="ContiguousMosaic">
    <xs:complexType/>
  </xs:element>
  <xs:element name="DoubleHeight">
    <xs:complexType/>
  </xs:element>
  <xs:element name="DoubleSize">
    <xs:complexType/>
  </xs:element>
  <xs:element name="DoubleWidth">
    <xs:complexType/>
  </xs:element>
  <xs:element name="EndBox">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Flash">
    <xs:complexType/>
  </xs:element>
  <xs:element name="HoldMosaic">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicBlack">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicBlue">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicCyan">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicGreen">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicMagenta">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicRed">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicWhite">
    <xs:complexType/>
  </xs:element>
  <xs:element name="MosaicYellow">
    <xs:complexType/>
  </xs:element>
  <xs:element name="NewBackground">
    <xs:complexType/>
  </xs:element>
  <xs:element name="NormalHeight">
    <xs:complexType/>
  </xs:element>
  <xs:element name="ReleaseMosaic">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Reserved">
    <xs:complexType/>
  </xs:element>
  <xs:element name="SeparatedMosaic">
    <xs:complexType/>
  </xs:element>
  <xs:element name="StartBox">
    <xs:complexType/>
  </xs:element>
  <xs:element name="Steady">
    <xs:complexType/>
  </xs:element>
  <xs:element name="newline">
    <xs:complexType/>
  </xs:element>
  <xs:element name="space">
    <xs:complexType/>
  </xs:element>
</xs:schema>

=== IRT-Open-Source/scf/modules/STLXML-XSD/tests/test_files/requirement-500-001-PASS.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--
Copyright 2016 Institut für Rundfunktechnik GmbH, Munich, Germany

Licensed under the Apache License, Version 2.0 (the "License"); 
you may not use this file except in compliance with the License.
You may obtain a copy of the License 

at http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, the subject work
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.

See the License for the specific language governing permissions and
limitations under the License.
-->

<!-- Testing StlXml-XSD with all elements possible -->
<StlXml xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="../../stlxml.xsd">
  <HEAD>
    <metadata>
      <UserDefinedElement1>Value</UserDefinedElement1>
      <UserDefinedElement2>Value</UserDefinedElement2>
    </metadata>
    <GSI>
      <CPN>850</CPN>
      <DFC>STL25.01</DFC>
      <DSC>2</DSC>
      <CCT>00</CCT>
      <LC>08</LC>
      <OPT>IRT Testsendung                 </OPT>
      <OET>IRT Testfolge                   </OET>
      <TPT>IRT Test Programme              </TPT>
      <TET>IRT Test Episode                </TET>
      <TN>Open Source Translator          </TN>
      <TCD>open.source@irt.de              </TCD>
      <SLR>ABC-4711        </SLR>
      <CD>151217</CD>
      <RD>151217</RD>
      <RN> 0</RN>
      <TNB>8    </TNB>
      <TNS>8    </TNS>
      <TNG>1  </TNG>
      <MNC>40</MNC>
      <MNR>23</MNR>
      <TCS>1</TCS>
      <TCP>10000000</TCP>
      <TCF>10000000</TCF>
      <TND>1</TND>
      <DSN>1</DSN>
      <CO>DEU</CO>
      <PUB>Institut für Rundfunktechnik    </PUB>
      <EN>Open Source Editor              </EN>
      <ECD>open.source@irt.de              </ECD>
      <UDA>UserDefinedData can contain anything. Max length: 768 
        50------------------------------------------------
        --------------------------------------------------
        --------------------------------------------------
        --------------------------------------------------
        --------------------------------------------------
        --------------------------------------------------
      </UDA>
    </GSI>
  </HEAD>
  <BODY>
    <TTICONTAINER>
      <TTI>
        <SGN>0</SGN>
        <SN>0</SN>
        <EBN>ff</EBN>
        <CS>00</CS>
        <TCI>10000000</TCI>
        <TCO>10000100</TCO>
        <VP>22</VP>
        <JC>02</JC>
        <CF>00</CF>
        <TF>
          All elements allowed in TextField:
          <BlackBackground/>
          <Conceal/>
          <ContiguousMosaic/>
          <DoubleHeight/>
          <DoubleSize/>
          <DoubleWidth/>
          <EndBox/>
          <Flash/>
          <HoldMosaic/>
          <MosaicBlack/>
          <MosaicBlue/>
          <MosaicCyan/>
          <MosaicGreen/>
          <MosaicMagenta/>
          <MosaicRed/>
          <MosaicWhite/>
          <MosaicYellow/>
          <NewBackground/>
          <NormalHeight/>
          <ReleaseMosaic/>
          <Reserved/>
          <SeparatedMosaic/>
          <StartBox/>
          <Steady/>
          <newline/>
          <space/>  
          <AlphaWhite/>
          <AlphaBlack/>
          <AlphaBlue/>
          <AlphaCyan/>
          <AlphaGreen/>
          <AlphaMagenta/>
          <AlphaRed/>
          <AlphaYellow/>
          <AlphaYellow/>
          <AlphaYellow/>
        </TF>
      </TTI>
      <TTI>
        <SGN>0</SGN>
        <SN>1</SN>
        <EBN>ff</EBN>
        <CS>00</CS>
        <TCI>10000200</TCI>
        <TCO>10000300</TCO>
        <VP>22</VP>
        <JC>02</JC>
        <CF>00</CF>
        <TF>
          Multiple TTI Blocks
        </TF>
      </TTI>
    </TTICONTAINER>
  </BODY>
</StlXml>
